# Generated by Django 5.1.5 on 2025-04-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='surface',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
